title: <p align="center"> Edson Carrasco</p>

logo: /assets/img/logo_1.png

description: <p align="center"> Civil Engineering Student </p>
  <p align="center">
  <a href="www.linkedin.com/in/edsonfabcs">LinkedIn</a> |
  <a href="https://github.com/KaizzerZz">Github Repository</a>
  </p>
  
  <p align="justify">
  Estudiante de 9no ciclo de la carrera de Ingeniería Civil en la Universidad Nacional de Ingeniería (UNI). Con conocimientos en ingeniería estructural e interés en automatización del análisis y diseño estructural sismorresistente, investigación en el área de estructuras y la metodología BIM.
  <br><br>
  Presidente de grupo estudiantil GADEST Estructuras.
  <br><br>
  </p>

google_analytics: G-ZZYG0XLBM7 
theme: jekyll-theme-architect
